### ISSUE TITLE
make install fails

### ISSUE THREAD

**Issue by andreas-roehler** [tvraman/emacspeak#18]
"sudo make install" of current trunk stops with "Symbol's value as variable is void: mpg123-mode-map "

Messages before are:

Loading emacspeak-metapost.elc...
Loading emacspeak-midge.elc...
Loading emacspeak-mpg123.elc...

**Comment by leavesofgrass** [comment]
I've run into the same issue trying to build emacspeak in a clean Debian testing VM. 
At first, I tried rolling back the emacspeak-mpg123.el a few weeks  (borrowing the file from a known working installation) and recompiling the .elc  locally but I continued to get the `Symbol's value as variable is void: mpg123-mode-map `
Since I'm working from a fresh minimal install, and I didn't have mpg123.el installed yet, I tried hitting up the MELPA for that next.
Unfortunately, even after a `make clean && make && make install`, the `Symbol's value as variable is void: mpg123-mode-map ` error persists and the `make install` operation hangs in the shell.

**Comment by leavesofgrass** [comment]
The newest commit is giving me a slightly different error with the same keymap:

"Loading emacspeak-metapost.elc...
Loading emacspeak-midge.elc...
Loading emacspeak-mpg123.elc...
Wrong type argument: keymapp, nil `

**Comment by andreas-roehler** [comment]
On 13.05.2016 22:44, leavesofgrass wrote:
>
> The newest commit is giving me a slightly different error with the 
> same keymap:
>
> "Loading emacspeak-metapost.elc...
> Loading emacspeak-midge.elc...
> Loading emacspeak-mpg123.elc...
> Wrong type argument: keymapp, nil `
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/tvraman/emacspeak/issues/18#issuecomment-219154532>
>

Got the second error too when playing here at my own.

Solved this by writing

(setq |mpg123-mode-map |(make-sparse-keymap))

Without understanding too much about the environment...

**Comment by tvraman** [comment]
closed:
