### ISSUE TITLE
Problem with make install.

### ISSUE THREAD

**Issue by BenKeyFSI** [tvraman/emacspeak#25]
Most people put the source code of any project they are working on in what is in essence a temporary location. They have ABSOLUTELY NO INTENTION of actually running the software from that location. This is why make install steps exist to copy the files to some other location. Your make install does not do this. You also provide no documentation on what is necessary for running and what is just necessary for building. If you are going to do something like this, please provide documentation on what files are necessary for running.

**Comment by juhp** [comment]
This seems to be a change in recent releases: eg 40.0 had `make install`.

I agree it would be nice to have it back though.

**Comment by MasseGuillaume** [comment]
It's since version 46.0

https://github.com/tvraman/emacspeak/commit/3df84c3188048485a7ed626971ccd3b70fc9ecb4#diff-b67911656ef5d18c4ae36cb6741b7965L240

I'm working on packaging emacspeak with a package manager called nix: https://github.com/NixOS/nixpkgs/pull/38343. It would be helpful for us to keep the install step.

**Comment by tvraman** [comment]
See the file 
etc/install.org	 for instructions.

for instructions for package managers.

I have no intent of bringing back a generic make install rule.
--

**Comment by tvraman** [comment]
closed: WAI
